import turtle
from turtle import*

import math
screen=turtle.Screen()
screen.bgcolor('black')
def rectangle(t, width, height, color):
  t.fillcolor(color)
  t.begin_fill()
  t.forward(width)
  t.left(90)
  t.forward(height)
  t.left(90)
  t.forward(width)
  t.left(90)
  t.forward(height)
  t.left(90)
  t.end_fill()
def parallelogram(t, width, height, color):
  t.fillcolor(color)
  t.begin_fill()
  t.left(30)
  t.forward(width)
  t.left(60)
  t.forward(height)
  t.left(120)
  t.forward(width)
  t.left(60)
  t.forward(height)
  t.left(90)
  t.end_fill()
def triangle(t, length, color):
  t.fillcolor(color)
  t.begin_fill()
  t.forward(length)
  t.left(135)
  t.forward(length / math.sqrt(2))
  t.left(90)
  t.forward(length / math.sqrt(2))
  t.left(135)
  t.end_fill()
def rev(t, length, color):
  t.fillcolor(color)
  t.begin_fill()
  t.backward(length)
  t.left(135)
  t.backward(length / math.sqrt(2))
  t.left(90)
  t.backward(length / math.sqrt(2))
  t.left(135)
  t.end_fill()


t=turtle.Turtle()
t.speed(4)
t.penup()

t.goto(-800,-600)
t.pendown()
rectangle(t,1600,600,'darkgreen')



t.penup()

t.goto(155,0)
t.pendown()
rectangle(t,50,60,'gray')
t.penup()
t.goto(205,0)
t.pendown()
rectangle(t,45,85,'gray')
t.penup()
t.goto(250,0)
t.pendown()
rectangle(t,40,105,'gray')
t.penup()
t.goto(290,0)
t.pendown()
rectangle(t,50,80,'gray')

t.penup()
t.goto(340,0)
t.pendown()
rectangle(t,40,65,'gray')

t.penup()
t.goto(380,0)
t.pendown()
rectangle(t,50,80,'gray')

t.penup()
t.goto(430,0)
t.pendown()
rectangle(t,45,115,'gray')

t.penup()
t.goto(475,0)
t.pendown()
rectangle(t,40,95,'gray')

t.penup()
t.goto(515,0)
t.pendown()
rectangle(t,35,70,'gray')

t.penup()
t.goto(550,0)
t.pendown()
rectangle(t,40,100,'gray')

t.penup()
t.goto(-80,0)
t.pendown()
rectangle(t,40,100,'gray')

t.penup()
t.goto(-125,0)
t.pendown()
rectangle(t,45,75,'gray')
t.penup()
t.goto(-160,0)
t.pendown()
rectangle(t,40,105,'gray')
t.penup()
t.goto(-290,0)
t.pendown()
rectangle(t,50,80,'gray')

t.penup()
t.goto(-330,0)
t.pendown()
rectangle(t,40,65,'gray')

t.penup()
t.goto(-370,0)
t.pendown()
rectangle(t,50,80,'gray')

t.penup()
t.goto(-350,-250)

rectangle(t,330,250,'brown')
t.penup()



t.goto(-35,-600)

t.pendown()
parallelogram(t,200,600,'black')
t.penup()
t.goto(30,-80)
t.pendown()
rectangle(t,15,80,'white')
t.penup()
t.goto(30,-210)
t.pendown()
rectangle(t,15,80,'white')
t.penup()
t.goto(-200,150)


t.fillcolor("grey")
t.pendown()
t.begin_fill()
t.circle(40)
t.end_fill()
t.penup()
t.goto(150,-130)
t.pendown()
rectangle(t,20,40,"brown")
t.penup()
t.goto(115,-90)
t.pendown()
triangle(t,90,'lightgreen')
t.penup()
t.goto(120,-50)
t.pendown()
triangle(t, 80, "lightgreen")
t.penup() 
t.goto(125, -10)
t.pendown()
triangle(t, 70, "lightgreen")
t.penup()

t.goto(250,-100)

t.pendown()
t.fillcolor('brown')
t.begin_fill()
k=20
for i in range (4):
    t.forward(50)
    t.right(90)
t.end_fill()
t.fillcolor('lightgreen')
t.begin_fill()
t.right(90)
t.forward(50)
t.left(90)
t.left(90)
t.forward(50)
t.right(90)
t.forward(125)
t.left(90)
t.forward(k)
for i in range(7):
    t.left(90)
    t.forward(k)
    t.right(90)
    t.forward(k)
    k=k-2
t.left(90)
t.forward(10)
t.left(90)
t.forward(15)
for i in range(9):
    t.right(90)
    t.forward(k)
    k=k+1
    t.left(90)
    t.forward(k)
t.forward(5)
t.left(90)
t.forward(75)
t.end_fill()
t.penup()


t.goto(-60,-130)
t.pendown()
rectangle(t,10,60,'white')
t.penup()
t.goto(-75,-130)
t.pendown()
triangle(t,40,'red')
t.penup()
t.goto(-30,-130)
t.pendown()
rectangle(t,10,60,'white')
t.penup()
t.goto(-45,-130)
t.pendown()
triangle(t,40,'red')
t.penup()
t.goto(-85,-70)
t.pendown()
triangle(t,100,'red')
t.penup()
t.goto(-5,5)
t.pendown()
rev(t,60,'blue')
t.penup()
t.goto(-40,5)
t.pendown()
rectangle(t,10,10,'white') #neck
t.penup()
t.goto(-35,15)

t.fillcolor("white")
t.pendown()
t.begin_fill()
t.circle(25)
t.end_fill()
t.penup()
t.goto(-45,65)
t.fillcolor('brown')

t.pendown()
t.begin_fill()

for i in range(3):
    t.forward(25)
    t.right(56)
    
t.end_fill()
t.goto(-35,65)
t.fillcolor('brown')


t.pendown()
t.begin_fill()

for i in range(2):
    t.forward(27)
    t.left(85)
    
t.end_fill()
t.penup()
t.goto(-5,-25)
t.pendown()
rectangle(t,8,30,'white')
t.penup()
t.goto(3,-25)
t.pendown()

rev(t,10,'white')
t.penup()
t.goto(-70,-25)
t.pendown()
rectangle(t,8,30,'white')
t.penup()
t.goto(-60,-25)
t.pendown()
rev(t,10,'white')
t.penup()
t.goto(-300,-65)
t.fillcolor('lightblue')


t.pendown()
t.begin_fill()

for i in range(4):
    t.forward(150)
    t.left(90)
    
t.end_fill()
t.penup()
t.goto(-295,-65)
t.pencolor('darkblue')


t.pendown()


for i in range(4):
    t.forward(140)
    t.left(90)
    

t.penup()
t.goto(-290,25)
t.pendown()
rectangle(t,120,30,'aqua')
t.penup()
t.goto(-310,-70)
t.pendown()
rectangle(t,170,10,'darkblue')
t.penup()
t.goto(-285,35)
t.pencolor('red')
t.pensize(2)
t.pendown()
t.write('       WORK','false','left','normal')
t.penup()

t.goto(55,110)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(-5,95)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(110,175)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(40,136)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(-15,150)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(287,245)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(5,200)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(-50,200)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(-85,175)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(-267,157)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(-306,148)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(-295,265)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144) 
t.end_fill()
t.penup()
t.goto(295,146)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(245,95)
t.pendown()
t.fillcolor('gray')
t.pensize(0)
t.pencolor('gray')
t.begin_fill()
for i in range(5):
    t.forward(10)
    t.right(144)
t.end_fill()
t.penup()
t.goto(245,195)
t.pendown()
t.pencolor('gray')

t.write('*Tonight I will stay tough,\nand maybe for once \nthey will see\nthat they can no longer hurt me*\n-Author unknown','false','right','normal')
t.penup()
t.goto(200,-200)
t.pencolor('black')
t.pendown()
t.write('#Reclaim the night','false','left','normal')





















